[package]
name = "todo-rust"
version = "0.1.0"
authors = ["RyoKojima <ryokojima@kojima.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
serde = "1.0"
serde_derive = "1.0.90"
diesel = { version = "1.3.0", features = ["mysql"] }
dotenv = "0.10"